### ISSUE TITLE
import other datasets

### ISSUE THREAD

**Issue by siyeonkim33** [brownvc/planit#2]
These days, I have a big interest in your work and want to apply it to my work.
However, it is hard to use your code because of an illegal dispute on SUNCG dataset.

I have spent a lot of time and effort to look at importing other datasets such as scan-net or nyu v2 with annotations, but it was not easy to work.
Is there any way that I can use your code?
Have you ever imported other datasets?

I need your help and advice.

**Comment by kwang-ether** [comment]
You could probably adapt the code for any dataset that contains scenes with obb&class labels for each object in the scene, though there need to be non trivial changes to the graph extraction / rendering process.
I am not currently aware of any alternative dataset (of a sufficient scale) that provides these, though

**Comment by youngmin1324** [comment]
안녕하세요 syunni33님!
저희는 syunni33님처럼 SUNCG 데이터셋 말고 다른 데이터셋을 적용해보려고 하는 한국 대학생들입니다.
혹시 해결하셨는지 여쭤봐도 될까요?
아래 연락처로 연락 주시면 정말 감사하겠습니다. ㅠㅠ

이메일: dldudals1324@gmail.com
카카오톡 ID: bhc79

**Comment by devShaurya** [comment]
Hi @kwang-ether could you please mention the major changes needed? 
Hi @syunni33 Were you able to import other datasets, could you please mention how did you achieve it?
