### ISSUE TITLE
Missing code about ramdom_graph()

### ISSUE THREAD

**Issue by hanamizukigakki** [brownvc/planit#3]
Hi, while processing the code, I found that in the script `scene-synth/graph_train.py`, the function `train()` calls the function `random_graph()`, but the definition of function `random_graph()` lost. I have searched the whole project, and found nothing. Could you please share this code with me ? Thanks

**Comment by kwang-ether** [comment]
code related to dataset handling were mostly removed in the released due to the issues mentioned in README
but basically - this just loads a random extracted graph for training
