### ISSUE TITLE
partial scene completion

### ISSUE THREAD

**Issue by youngmin1324** [brownvc/planit#4]
I want to make a complete scene from a partial scene. I tried to use the complete_room() in graph_synth.py but it seems that the constructor parameter of the SynthRoom class is wrong and the code is not implemented. What should I do?

**Comment by kwang-ether** [comment]
It is indeed not implemented - complete_room() was used for an earlier work.
To do partial room completion, you would need to first build the partial graph from the scene, and then feed it to the graph generative model to complete the graph (note that you would still need to start the generative model from walls only and teacher force the first steps until you get to the partial graph)
Then run the synth pipeline with the completed graph, and manually initialize the first few SynthSteps to be the objects from the partial scene.
I think that's probably the way I did it.. I don't remember where that code is... It was a last last minute hack....
