### ISSUE TITLE
Instructions on creating the dataset and training

### ISSUE THREAD

**Issue by fbhdr** [brownvc/planit#7]
Hi, I wonder how the dataset is generated. From my understanding, this repo only provides some tools for dataset generation but lacks a main script for calling the tools, something like [create_data.py](https://github.com/brownvc/deep-synth/blob/master/deep-synth/create_data.py) in [deep-synth](https://github.com/brownvc/deep-synth). Is my understanding correct?

I know SUNCG is not publicly available now but I have downloaded the dataset. In addition, I find it possible to run fast-synth with some existing available datasets and I am able to turn some existing datasets to SUNCG format. Since your codes are not related to SUNCG license, can you provide instructions and codes on generating the dataset?

It is also appreciated if you could provide instructions on running the codes, e.g. the training/testing commands/flags you use in the original paper.

Thanks!

**Comment by fathyshalaby** [comment]
When I run the graph_train it says that random_graph() is not defined and that is true. Is there a reason why? The code should be runnable I assume right? Also I noticed that in the same python file you have the following:
if test_epoch >= 0:
    with open(f"{load_dir}/config.pkl", 'rb') as f:
        config = pickle.load(f)
        print(config)
else:
    with open(f"{save_dir}/config.pkl", 'wb') as f:
        pickle.dump(config, f, pickle.HIGHEST_PROTOCOL)
and set test_epoch as 65. Could you please explain why I read in a config file which is still needs to be created and is predefined in the same python file?
